services:
  web:
    build: .
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - default
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
    ports:
      - "3307:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - default
